import type { WizardStep } from "./PlatformWizard";

export const FACEBOOK_STEPS: WizardStep[] = [
  {
    title: "Criar Pixel no Business Manager",
    subtitle: "O Pixel ID é o identificador do seu container de eventos",
    explanation: [
      "O primeiro passo é criar um Pixel (ou Dataset) no Meta Business Manager. É ele que recebe todos os eventos (PageView, Purchase, Lead, etc).",
      "**Como fazer:**",
      "- Acesse business.facebook.com → Events Manager",
      "- Clique em 'Conectar fontes de dados' → Web",
      "- Escolha 'Meta Pixel' e dê um nome (ex: 'Meu Site - Pixel')",
      "- Copie o Pixel ID (número de 15-16 dígitos, ex: 1234567890123456)",
      "Guarde esse ID — você vai usar na configuração do CapiTrack.",
    ],
    tip: "Se você já tem um Pixel criado, basta pegar o ID dele no Events Manager → Settings.",
    referenceLinks: [
      { label: "Events Manager", url: "https://business.facebook.com/events_manager2" },
      { label: "Doc: Criar Pixel", url: "https://www.facebook.com/business/help/952192354843755" },
    ],
  },
  {
    title: "Gerar Access Token (CAPI)",
    subtitle: "Token de acesso para enviar eventos server-side",
    explanation: [
      "Para enviar eventos pela Conversions API (CAPI), você precisa de um Access Token com permissão de escrita no Pixel.",
      "**Como gerar:**",
      "- No Events Manager, selecione seu Pixel",
      "- Vá em Settings → Conversions API",
      "- Clique em 'Generate Access Token'",
      "- Copie o token gerado (string longa começando com 'EAA...')",
      "**Importante:** Esse token NÃO expira, mas mantenha-o seguro. Nunca exponha no frontend.",
      "Se preferir mais controle, você pode gerar via System User no Business Settings → Users → System Users → Generate Token com a permissão 'ads_management'.",
    ],
    tip: "O método mais rápido é gerar direto no Events Manager. O System User é recomendado para produção em escala.",
    referenceLinks: [
      { label: "Events Manager → Settings", url: "https://business.facebook.com/events_manager2" },
      { label: "Doc: Access Token CAPI", url: "https://developers.facebook.com/docs/marketing-api/conversions-api/get-started#access-token" },
      { label: "Doc: System User", url: "https://www.facebook.com/business/help/503306463479099" },
    ],
  },
  {
    title: "Configurar Destino Meta no CapiTrack",
    subtitle: "Cole o Pixel ID e Access Token nas integrações",
    explanation: [
      "Agora você vai cadastrar o Meta como destino de eventos no CapiTrack.",
      "**Como fazer:**",
      "- Vá em Integrações no menu lateral",
      "- Clique em 'Meta / Facebook CAPI'",
      "- Cole o Pixel ID e o Access Token que você gerou",
      "- Ative o destino",
      "O CapiTrack vai automaticamente enviar Purchase, Lead, PageView e outros eventos para a Meta CAPI com batching (até 1000 eventos por request), retries automáticos e hashing SHA-256 dos dados pessoais (email, telefone).",
    ],
    tip: "Após configurar, você pode verificar o status do envio na página de Integration Logs.",
    actionLabel: "Ir para Integrações",
    actionRoute: "/integrations",
  },
  {
    title: "Instalar o SDK no seu site",
    subtitle: "Copie o snippet e cole no HTML do seu site",
    explanation: [
      "O SDK captura automaticamente PageView, UTMs, click IDs (fbclid), cookies (_fbp, _fbc) e fingerprint do navegador.",
      "**Como instalar:**",
      "- Vá em SDK Setup no menu lateral",
      "- Copie o snippet gerado com sua API Key",
      "- Cole antes do </head> no HTML do seu site",
      "Para rastrear eventos customizados (Purchase, Lead), use:",
    ],
    copySnippet: `capitrack("track", "Purchase", {
  value: 297.00,
  currency: "BRL",
  email: "cliente@email.com"
});`,
    tip: "Funciona com qualquer site: WordPress, Shopify, HTML estático, React, etc. No WordPress, use o plugin 'Insert Headers and Footers'.",
    actionLabel: "Copiar SDK",
    actionRoute: "/sdk-setup",
  },
  {
    title: "Verificar Eventos no Events Manager",
    subtitle: "Confirme que os eventos estão chegando na Meta",
    explanation: [
      "Após instalar o SDK e configurar o destino, os eventos devem aparecer no Events Manager da Meta em até 20 minutos.",
      "**Como verificar:**",
      "- Acesse Events Manager → seu Pixel",
      "- Vá na aba 'Test Events' (Testar Eventos)",
      "- Abra seu site em outra aba e faça ações (navegação, compra teste)",
      "- Os eventos devem aparecer em tempo real na tela de teste",
      "**Checklist de validação:**",
      "- ✅ PageView aparecendo",
      "- ✅ Eventos customizados (Purchase, Lead) com valores corretos",
      "- ✅ Parâmetros de usuário (em, ph) mostrando 'Match Quality: Great'",
      "- ✅ action_source = 'website' (indica server-side)",
      "Se algo não aparecer, verifique os Event Logs no CapiTrack para ver se houve erro no envio.",
    ],
    tip: "A aba 'Test Events' mostra eventos em tempo real. A aba 'Overview' pode levar até 20min para atualizar.",
    referenceLinks: [
      { label: "Events Manager → Test Events", url: "https://business.facebook.com/events_manager2" },
      { label: "Doc: Testar CAPI", url: "https://developers.facebook.com/docs/marketing-api/conversions-api/using-the-api#test-events" },
    ],
    actionLabel: "Ver Event Logs",
    actionRoute: "/event-logs",
  },
  {
    title: "Configurar Eventos de Conversão",
    subtitle: "Otimize suas campanhas com os eventos certos",
    explanation: [
      "Agora que os eventos estão chegando, configure quais deles são usados como conversão nas campanhas.",
      "**No Ads Manager:**",
      "- Ao criar uma campanha, em 'Conversion Event', selecione o evento desejado (Purchase, Lead, etc)",
      "- Se o evento não aparecer, volte ao Events Manager → Custom Conversions e crie uma",
      "**Eventos padrão recomendados para otimização:**",
      "- Purchase — Para campanhas de venda",
      "- Lead / CompleteRegistration — Para geração de leads",
      "- AddToCart / InitiateCheckout — Para remarketing",
      "- ViewContent — Para campanhas de topo de funil",
      "**Domínio verificado (importante):**",
      "- Em Business Settings → Brand Safety → Domains, adicione e verifique seu domínio",
      "- Isso é obrigatório desde o iOS 14.5 para priorização de eventos",
    ],
    tip: "Com server-side tracking via CAPI, seu Event Match Quality sobe significativamente, melhorando o ROAS das campanhas.",
    referenceLinks: [
      { label: "Doc: Eventos Padrão", url: "https://developers.facebook.com/docs/meta-pixel/reference" },
      { label: "Doc: Verificar Domínio", url: "https://developers.facebook.com/docs/sharing/domain-verification" },
      { label: "Doc: Aggregated Event Measurement", url: "https://developers.facebook.com/docs/marketing-apis/conversions-api/deduplicate-pixel-and-server-events" },
    ],
  },
];
