import type { WizardStep } from "./PlatformWizard";

export const GOOGLE_STEPS: WizardStep[] = [
  {
    title: "Criar Propriedade GA4",
    subtitle: "O GA4 é onde seus dados de analytics ficam centralizados",
    explanation: [
      "O Google Analytics 4 (GA4) é a base para rastrear eventos e conversões do Google.",
      "**Como criar:**",
      "- Acesse analytics.google.com",
      "- Clique em 'Admin' (engrenagem) → 'Create Property'",
      "- Preencha: Nome da propriedade, fuso horário, moeda (BRL)",
      "- Em 'Data Collection', escolha 'Web'",
      "- Informe a URL do seu site e dê um nome ao Data Stream",
      "Após criar, você terá um Measurement ID (formato: G-XXXXXXXXXX).",
    ],
    tip: "Se você já tem uma propriedade GA4, basta pegar o Measurement ID em Admin → Data Streams → seu stream.",
    referenceLinks: [
      { label: "Google Analytics", url: "https://analytics.google.com" },
      { label: "Doc: Criar Propriedade GA4", url: "https://support.google.com/analytics/answer/9304153" },
    ],
  },
  {
    title: "Gerar API Secret (Measurement Protocol)",
    subtitle: "Chave para enviar eventos server-side para o GA4",
    explanation: [
      "O Measurement Protocol permite enviar eventos diretamente do servidor para o GA4, sem depender do navegador.",
      "**Como gerar:**",
      "- No GA4, vá em Admin → Data Streams → selecione seu stream",
      "- Role até 'Measurement Protocol API Secrets'",
      "- Clique em 'Create' e dê um nome (ex: 'CapiTrack Server')",
      "- Copie o API Secret gerado",
      "Você precisará de duas informações:",
      "- **Measurement ID**: G-XXXXXXXXXX (visível no topo do Data Stream)",
      "- **API Secret**: string alfanumérica gerada acima",
    ],
    tip: "Cada API Secret pode ser revogado individualmente, então crie um exclusivo para o CapiTrack.",
    referenceLinks: [
      { label: "GA4 Admin → Data Streams", url: "https://analytics.google.com" },
      { label: "Doc: Measurement Protocol", url: "https://developers.google.com/analytics/devguides/collection/protocol/ga4" },
      { label: "Doc: API Secret", url: "https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events#required_parameters" },
    ],
  },
  {
    title: "Configurar Destino GA4 no CapiTrack",
    subtitle: "Cole o Measurement ID e API Secret nas integrações",
    explanation: [
      "Cadastre o GA4 como destino de eventos no CapiTrack.",
      "**Como fazer:**",
      "- Vá em Integrações no menu lateral",
      "- Clique em 'Google Analytics 4 (GA4)'",
      "- Cole o Measurement ID (G-XXXXXXXXXX) e o API Secret",
      "- Ative o destino",
      "O CapiTrack enviará automaticamente os eventos via Measurement Protocol, incluindo client_id, session_id e parâmetros customizados.",
    ],
    tip: "O GA4 pode levar até 24h para exibir dados no relatório padrão. Use o 'Realtime' para verificar imediatamente.",
    actionLabel: "Ir para Integrações",
    actionRoute: "/integrations",
  },
  {
    title: "Vincular Google Ads ao GA4",
    subtitle: "Importe conversões do GA4 para otimizar campanhas",
    explanation: [
      "Para usar os eventos como conversão no Google Ads, você precisa vincular as duas contas.",
      "**Como vincular:**",
      "- No GA4, vá em Admin → Product Links → Google Ads",
      "- Clique em 'Link' e selecione sua conta Google Ads",
      "- Ative 'Enable Personalized Advertising'",
      "- No Google Ads, vá em Tools → Conversions → Import",
      "- Selecione 'Google Analytics 4' e importe os eventos desejados",
      "**Eventos que geralmente importamos como conversão:**",
      "- purchase → Para campanhas de venda (valor dinâmico)",
      "- generate_lead → Para campanhas de lead",
      "- begin_checkout → Para otimização de funil",
    ],
    tip: "Marque 'Use enhanced conversions' no Google Ads para melhorar o match rate com dados server-side (email, phone).",
    referenceLinks: [
      { label: "Google Ads → Conversions", url: "https://ads.google.com/aw/conversions" },
      { label: "Doc: Vincular GA4 + Ads", url: "https://support.google.com/analytics/answer/9379420" },
      { label: "Doc: Import Conversions", url: "https://support.google.com/google-ads/answer/2375435" },
    ],
  },
  {
    title: "Criar Conversão no Google Ads (Enhanced Conversions)",
    subtitle: "Configure o ID da conversão e a label para tracking direto",
    explanation: [
      "Além de importar do GA4, você pode enviar conversões diretamente para o Google Ads via Enhanced Conversions API.",
      "**Como criar a conversão:**",
      "- No Google Ads, vá em Tools & Settings → Conversions",
      "- Clique em '+ New Conversion Action' → Website",
      "- Configure: Nome, Valor (use 'Use different values'), Contagem",
      "- Após criar, copie:",
      "- **Conversion ID**: número (ex: AW-123456789)",
      "- **Conversion Label**: string (ex: AbCdEfGhIjKlMnOp)",
      "Esses valores são usados pelo CapiTrack para enviar conversões server-side diretamente para o Google Ads.",
      "**Para configurar no CapiTrack:**",
      "- Vá em Integrações → Google Ads",
      "- Cole o Conversion ID e Label",
      "- Ative Enhanced Conversions",
    ],
    tip: "Enhanced Conversions usa dados hasheados (email, phone) para melhorar a atribuição. O CapiTrack já faz o hashing SHA-256 automaticamente.",
    referenceLinks: [
      { label: "Google Ads → Conversions", url: "https://ads.google.com/aw/conversions" },
      { label: "Doc: Enhanced Conversions", url: "https://developers.google.com/google-ads/api/docs/conversions/enhance-conversions" },
      { label: "Doc: Conversion Tracking", url: "https://support.google.com/google-ads/answer/1722054" },
    ],
    actionLabel: "Ir para Integrações",
    actionRoute: "/integrations",
  },
  {
    title: "Instalar SDK e Verificar",
    subtitle: "Confirme que os dados estão chegando no GA4 e Google Ads",
    explanation: [
      "Se ainda não instalou o SDK, faça isso agora (mesmo snippet para todas as plataformas).",
      "**Verificar no GA4:**",
      "- Acesse analytics.google.com → Realtime",
      "- Abra seu site e faça ações (navegação, compra teste)",
      "- Os eventos devem aparecer em tempo real",
      "**Verificar no Google Ads:**",
      "- Em Conversions, verifique a coluna 'Status'",
      "- Deve mostrar 'Recording conversions' ou 'Recently active'",
      "- Pode levar até 24-48h para atualizar o status",
      "**Checklist de validação:**",
      "- ✅ GA4 Realtime mostrando eventos (page_view, purchase)",
      "- ✅ Parâmetros chegando corretamente (value, currency, transaction_id)",
      "- ✅ Google Ads conversão com status 'Recording'",
      "- ✅ Event Logs do CapiTrack sem erros de envio",
    ],
    tip: "O GA4 Realtime atualiza em segundos. Os relatórios completos levam até 24h. O Google Ads pode levar 48h para confirmar.",
    referenceLinks: [
      { label: "GA4 Realtime", url: "https://analytics.google.com" },
      { label: "Google Ads Conversions", url: "https://ads.google.com/aw/conversions" },
    ],
    actionLabel: "Ver Event Logs",
    actionRoute: "/event-logs",
  },
];
