import type { WizardStep } from "./PlatformWizard";

export const GOOGLE_STEPS: WizardStep[] = [
  {
    title: "Criar Propriedade GA4",
    subtitle: "O GA4 é onde seus dados de analytics ficam centralizados",
    explanation: [
      "O Google Analytics 4 (GA4) é a base para rastrear eventos e conversões do Google.",
      "**Como criar:**",
      "- Acesse analytics.google.com",
      "- Clique em 'Admin' (engrenagem) → 'Create Property'",
      "- Preencha: Nome da propriedade, fuso horário, moeda (BRL)",
      "- Em 'Data Collection', escolha 'Web'",
      "- Informe a URL do seu site e dê um nome ao Data Stream",
    ],
    inputs: [
      {
        id: "ga4_measurement_id",
        label: "Measurement ID",
        placeholder: "G-XXXXXXXXXX",
        helpText: "Encontrado em Admin → Data Streams → seu stream (formato G-XXXXXXXXXX)",
        validation: /^G-[A-Z0-9]{8,12}$/,
        validationMessage: "O Measurement ID deve seguir o formato G-XXXXXXXXXX",
      },
    ],
    tip: "Se você já tem uma propriedade GA4, basta pegar o Measurement ID em Admin → Data Streams → seu stream.",
    referenceLinks: [
      { label: "Google Analytics", url: "https://analytics.google.com" },
      { label: "Doc: Criar Propriedade GA4", url: "https://support.google.com/analytics/answer/9304153" },
    ],
  },
  {
    title: "Ativar APIs no Google Cloud (obrigatório)",
    subtitle: "Sem isso, o CapiTrack não consegue ler dados nem listar propriedades do GA4",
    explanation: [
      "Para o CapiTrack ler relatórios e configurações do GA4, você precisa **ativar 2 APIs gratuitas** no projeto Google Cloud que está vinculado à sua conta Google.",
      "Se você pular este passo, vai aparecer o erro: *\"Google Analytics Data API has not been used in project XXX before or it is disabled\"* (HTTP 403).",
      "**Como ativar (1 minuto):**",
      "- Acesse https://console.cloud.google.com/ e faça login com a **mesma conta Google** que usa no GA4",
      "- No topo, selecione (ou crie) um **projeto** — ex: 'CapiTrack'",
      "- Abra este link e clique em **ENABLE / ATIVAR**: https://console.developers.google.com/apis/api/analyticsdata.googleapis.com",
      "- Abra também e clique em **ENABLE / ATIVAR**: https://console.developers.google.com/apis/api/analyticsadmin.googleapis.com",
      "- Aguarde **1 a 2 minutos** para o Google propagar a ativação",
      "- Volte no CapiTrack em **GA4 Analytics** e clique no botão de refresh 🔄",
    ],
    tip: "Use o mesmo projeto Google Cloud que você já usa para Google Ads — uma única ativação serve para todas as integrações.",
    referenceLinks: [
      { label: "Ativar Data API", url: "https://console.developers.google.com/apis/api/analyticsdata.googleapis.com" },
      { label: "Ativar Admin API", url: "https://console.developers.google.com/apis/api/analyticsadmin.googleapis.com" },
      { label: "Google Cloud Console", url: "https://console.cloud.google.com/" },
    ],
  },
  {
    title: "Gerar API Secret (Measurement Protocol)",
    subtitle: "Chave para enviar eventos server-side para o GA4",
    explanation: [
      "O Measurement Protocol permite enviar eventos diretamente do servidor para o GA4, sem depender do navegador.",
      "**Como gerar:**",
      "- No GA4, vá em Admin → Data Streams → selecione seu stream",
      "- Role até 'Measurement Protocol API Secrets'",
      "- Clique em 'Create' e dê um nome (ex: 'CapiTrack Server')",
      "- Copie o API Secret gerado",
    ],
    inputs: [
      {
        id: "ga4_api_secret",
        label: "API Secret (Measurement Protocol)",
        placeholder: "xxxxxxxxxxxxxxxxxxxxxxxx",
        type: "password",
        helpText: "String alfanumérica gerada em Data Streams → Measurement Protocol API Secrets",
        validation: /^.{8,}$/,
        validationMessage: "O API Secret deve ter pelo menos 8 caracteres",
      },
    ],
    tip: "Cada API Secret pode ser revogado individualmente, então crie um exclusivo para o CapiTrack.",
    referenceLinks: [
      { label: "GA4 Admin → Data Streams", url: "https://analytics.google.com" },
      { label: "Doc: Measurement Protocol", url: "https://developers.google.com/analytics/devguides/collection/protocol/ga4" },
      { label: "Doc: API Secret", url: "https://developers.google.com/analytics/devguides/collection/protocol/ga4/sending-events#required_parameters" },
    ],
  },
  {
    title: "Configurar Destino GA4 no CapiTrack",
    subtitle: "Cole o Measurement ID e API Secret nas integrações",
    explanation: [
      "Cadastre o GA4 como destino de eventos no CapiTrack.",
      "**Como fazer:**",
      "- Vá em Integrações no menu lateral",
      "- Clique em 'Google Analytics 4 (GA4)'",
      "- Cole o Measurement ID e o API Secret",
      "- Ative o destino",
      "O CapiTrack enviará automaticamente os eventos via Measurement Protocol.",
    ],
    tip: "O GA4 pode levar até 24h para exibir dados no relatório padrão. Use o 'Realtime' para verificar imediatamente.",
    actionLabel: "Ir para Integrações",
    actionRoute: "/integrations",
  },
  {
    title: "Criar Conta MCC (Manager) — Necessário para Developer Token",
    subtitle: "O Developer Token só é gerado em contas Manager (MCC)",
    explanation: [
      "Se ao acessar a Central de API aparecer 'disponível apenas para contas de administrador', você precisa criar uma conta MCC (Manager Account). É 100% gratuita.",
      "**Como criar a MCC corretamente:**",
      "- Acesse https://ads.google.com/home/tools/manager-accounts/",
      "- Clique em 'Criar uma conta de administrador'",
      "- **Nome**: ex. 'CapiTrack Manager'",
      "- **Esta conta será usada para**: selecione **'Gerenciar contas de outras pessoas'** ⚠️ (NÃO escolha 'minha própria conta')",
      "- **País**: Brasil | **Fuso**: GMT-03:00 Brasília | **Moeda**: BRL (não dá para mudar depois!)",
      "- Clique em 'Enviar' — você receberá um novo Customer ID (XXX-XXX-XXXX)",
      "**Como vincular sua conta normal à MCC:**",
      "- Estando logado na MCC, no menu esquerdo clique no **ícone de Contas** (👥)",
      "- Abra **'Configurações da subconta'** (NÃO é em 'Acesso e segurança → Usuários')",
      "- Clique no botão **+** (azul) → **'Vincular conta existente'**",
      "- Cole o Customer ID da conta normal (ex: 909-234-6354) → 'Enviar solicitação'",
      "- Faça login na conta normal e **aceite o convite** em Configurações → Administradores",
    ],
    tip: "Se não aparecer 'Configurações da subconta' no menu, você não está logado na MCC. Troque pelo avatar no canto superior direito.",
    referenceLinks: [
      { label: "Criar conta MCC", url: "https://ads.google.com/home/tools/manager-accounts/" },
      { label: "Doc: Vincular contas à MCC", url: "https://support.google.com/google-ads/answer/7459601?hl=pt-BR" },
      { label: "Doc: Sobre contas MCC", url: "https://support.google.com/google-ads/answer/6139186?hl=pt-BR" },
    ],
  },
  {
    title: "Vincular Google Ads ao GA4 (passo a passo atualizado)",
    subtitle: "Importe conversões do GA4 para otimizar campanhas — layout 2026",
    explanation: [
      "Para usar os eventos como conversão no Google Ads, você precisa vincular as duas contas. O layout do GA4 mudou, siga exatamente este caminho:",
      "**📊 PARTE 1 — No GA4 (analytics.google.com):**",
      "- Clique em **Admin** (engrenagem ⚙️ no canto inferior esquerdo)",
      "- No menu lateral esquerdo, role até a seção **'Vínculos de produtos'** (fica abaixo de 'Exibição de dados')",
      "- Clique em **'Vinculações do Google Ads'**",
      "- Clique no botão azul **'Vincular'** (canto superior direito)",
      "- Clique em **'Escolher contas do Google Ads'** → selecione sua conta MCC → **'Confirmar'**",
      "- Clique em **'Próxima'**",
      "- ✅ Ative **'Ativar publicidade personalizada'**",
      "- ✅ Ative **'Ativar marcação automática'** (recomendado)",
      "- Clique em **'Próxima'** → **'Enviar'** ✓",
      "**🎯 PARTE 2 — No Google Ads (ads.google.com):**",
      "- No menu superior, clique em **Ferramentas 🔧** → **Conversões** (em 'Medição')",
      "- Clique no botão azul **'+ Nova ação de conversão'**",
      "- Na tela 'Escolha as fontes de dados', marque **'Conversões em um site'** (e DESMARQUE 'Conversões de chamadas telefônicas' se vier marcado)",
      "- Clique em **'Editar fontes de dados'** → digite a URL do seu site → **'Verificar'**",
      "- Marque **AS DUAS** fontes que aparecerem: a tag do Google Ads (AW-...) E a propriedade GA4 → **'Concluído'**",
      "- Clique em **'Salvar e continuar'**",
      "- Na tela seguinte, **selecione os eventos do GA4** que quer importar como conversão (ex: `purchase`, `add_to_cart`, `begin_checkout`)",
      "- Atribua a **categoria** correta (ex: purchase = 'Compra') → **'Salvar e continuar'**",
      "- Na última tela ('Termine a configuração'), clique em **'Finalizar'** ✅",
      "**⚠️ IMPORTANTE:** Só aparecem na lista os eventos que **já foram disparados** no seu site nos últimos 28 dias. Se faltar algum (ex: `begin_checkout`), instale o SDK primeiro e volte depois.",
    ],
    inputs: [
      {
        id: "gads_customer_id",
        label: "Google Ads Customer ID",
        placeholder: "123-456-7890",
        helpText: "📍 Onde achar: no canto superior DIREITO do Google Ads, LOGO ACIMA do seu e-mail (ex: aparece '909-234-6354' acima de 'seuemail@gmail.com'). Formato: XXX-XXX-XXXX. ⚠️ Use o ID da CONTA NORMAL (onde rodam as campanhas), NÃO da MCC Manager.",
        validation: /^\d{3}-\d{3}-\d{4}$/,
        validationMessage: "O Customer ID deve seguir o formato XXX-XXX-XXXX",
      },
    ],
    tip: "Marque 'Use enhanced conversions' no Google Ads para melhorar o match rate com dados server-side.",
    referenceLinks: [
      { label: "Google Ads → Conversions", url: "https://ads.google.com/aw/conversions" },
      { label: "Doc: Vincular GA4 + Ads", url: "https://support.google.com/analytics/answer/9379420" },
      { label: "Doc: Import Conversions", url: "https://support.google.com/google-ads/answer/2375435" },
    ],
  },
  {
    title: "Criar Conversão no Google Ads (Enhanced Conversions)",
    subtitle: "Configure o ID da conversão e a label para tracking direto",
    explanation: [
      "Além de importar do GA4, você pode enviar conversões diretamente para o Google Ads via Enhanced Conversions API.",
      "**Como criar a conversão:**",
      "- No Google Ads, vá em Tools & Settings → Conversions",
      "- Clique em '+ New Conversion Action' → Website",
      "- Configure: Nome, Valor, Contagem",
      "- Após criar, copie o Conversion ID e Label",
    ],
    inputs: [
      {
        id: "gads_conversion_id",
        label: "Conversion ID",
        placeholder: "AW-123456789",
        helpText: "Formato AW-XXXXXXXXX, encontrado após criar a conversão",
        validation: /^AW-\d{6,12}$/,
        validationMessage: "O Conversion ID deve seguir o formato AW-XXXXXXXXX",
      },
      {
        id: "gads_conversion_label",
        label: "Conversion Label",
        placeholder: "AbCdEfGhIjKlMnOp",
        helpText: "String alfanumérica gerada junto com o Conversion ID",
        validation: /^[A-Za-z0-9_-]{6,}$/,
        validationMessage: "O Conversion Label deve ter pelo menos 6 caracteres alfanuméricos",
      },
    ],
    tip: "Enhanced Conversions usa dados hasheados (email, phone) para melhorar a atribuição. O CapiTrack já faz o hashing SHA-256 automaticamente.",
    referenceLinks: [
      { label: "Google Ads → Conversions", url: "https://ads.google.com/aw/conversions" },
      { label: "Doc: Enhanced Conversions", url: "https://developers.google.com/google-ads/api/docs/conversions/enhance-conversions" },
      { label: "Doc: Conversion Tracking", url: "https://support.google.com/google-ads/answer/1722054" },
    ],
    actionLabel: "Ir para Integrações",
    actionRoute: "/integrations",
  },
  {
    title: "Instalar SDK e Verificar",
    subtitle: "Confirme que os dados estão chegando no GA4 e Google Ads",
    explanation: [
      "Se ainda não instalou o SDK, faça isso agora (mesmo snippet para todas as plataformas).",
      "**Verificar no GA4:**",
      "- Acesse analytics.google.com → Realtime",
      "- Abra seu site e faça ações (navegação, compra teste)",
      "- Os eventos devem aparecer em tempo real",
      "**Checklist de validação:**",
      "- ✅ GA4 Realtime mostrando eventos (page_view, purchase)",
      "- ✅ Parâmetros chegando corretamente (value, currency, transaction_id)",
      "- ✅ Google Ads conversão com status 'Recording'",
      "- ✅ Event Logs do CapiTrack sem erros de envio",
    ],
    inputs: [
      {
        id: "ga4_site_url",
        label: "URL do seu site",
        placeholder: "https://www.seusite.com.br",
        helpText: "Domínio onde o SDK será instalado para verificação",
        validation: /^https?:\/\/.+/,
        validationMessage: "Informe uma URL válida",
      },
    ],
    tip: "O GA4 Realtime atualiza em segundos. O Google Ads pode levar 48h para confirmar.",
    referenceLinks: [
      { label: "GA4 Realtime", url: "https://analytics.google.com" },
      { label: "Google Ads Conversions", url: "https://ads.google.com/aw/conversions" },
    ],
    actionLabel: "Ver Event Logs",
    actionRoute: "/event-logs",
  },
];
